/**
 * Generates instant realistic sample media (Images and Animated Videos)
 * with watermarks for quick testing in 1-click.
 */

export class SampleMediaGenerator {
  /**
   * Generates a sample image with an AI watermark in the bottom-right corner
   */
  public static async createSampleImage(provider: 'Veo 3' | 'Gemini' | 'Flow AI'): Promise<File> {
    const canvas = document.createElement('canvas');
    const width = 1280;
    const height = 720;
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext('2d')!;

    // Draw rich scenic background gradient
    const grad = ctx.createLinearGradient(0, 0, width, height);
    if (provider === 'Veo 3') {
      grad.addColorStop(0, '#0f172a');
      grad.addColorStop(0.5, '#1e293b');
      grad.addColorStop(1, '#0c4a6e');
    } else if (provider === 'Gemini') {
      grad.addColorStop(0, '#180a29');
      grad.addColorStop(0.5, '#3b0764');
      grad.addColorStop(1, '#1e1b4b');
    } else {
      grad.addColorStop(0, '#111827');
      grad.addColorStop(0.5, '#1f2937');
      grad.addColorStop(1, '#374151');
    }
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, width, height);

    // Draw glowing visual elements
    for (let i = 0; i < 20; i++) {
      ctx.beginPath();
      const x = Math.random() * width;
      const y = Math.random() * height;
      const r = 20 + Math.random() * 80;
      ctx.arc(x, y, r, 0, Math.PI * 2);
      ctx.fillStyle = `hsla(${(i * 35) % 360}, 70%, 55%, 0.15)`;
      ctx.fill();
    }

    // Draw main label in center
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 36px "Plus Jakarta Sans", sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(`AI Media Showcase - Generated by ${provider}`, width / 2, height / 2 - 20);

    ctx.fillStyle = '#94a3b8';
    ctx.font = '18px "Plus Jakarta Sans", sans-serif';
    ctx.fillText('Nhấn "✨ Remove Watermark Now" để xem thuật toán xóa vùng khoanh đỏ', width / 2, height / 2 + 25);

    // Draw realistic Watermark in bottom right
    this.drawWatermarkBadge(ctx, width, height, provider);

    return new Promise((resolve) => {
      canvas.toBlob((blob) => {
        const file = new File([blob!], `sample_${provider.toLowerCase().replace(/\s+/g, '_')}_720p.png`, {
          type: 'image/png',
        });
        resolve(file);
      }, 'image/png');
    });
  }

  /**
   * Generates a 3-second animated sample video with an AI watermark
   */
  public static async createSampleVideo(provider: 'Veo 3' | 'Gemini' | 'Flow AI'): Promise<File> {
    const canvas = document.createElement('canvas');
    const width = 854;
    const height = 480;
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext('2d')!;

    const stream = canvas.captureStream(30);
    const recorder = new MediaRecorder(stream, {
      mimeType: MediaRecorder.isTypeSupported('video/webm;codecs=vp9') ? 'video/webm;codecs=vp9' : 'video/webm',
    });

    const chunks: Blob[] = [];
    recorder.ondataavailable = (e) => {
      if (e.data.size > 0) chunks.push(e.data);
    };

    recorder.start();

    // Render 90 frames (~3 seconds)
    for (let frame = 0; frame < 90; frame++) {
      const time = frame / 30;

      // Animated background
      const grad = ctx.createLinearGradient(
        Math.sin(time) * 200,
        0,
        width + Math.cos(time) * 200,
        height
      );
      grad.addColorStop(0, '#0f172a');
      grad.addColorStop(0.5, '#1e1b4b');
      grad.addColorStop(1, '#042f2e');
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, width, height);

      // Animated moving particles
      for (let i = 0; i < 15; i++) {
        const px = (width / 2) + Math.sin(time * 2 + i) * (150 + i * 15);
        const py = (height / 2) + Math.cos(time * 1.5 + i) * (80 + i * 10);
        ctx.beginPath();
        ctx.arc(px, py, 12 + i * 2, 0, Math.PI * 2);
        ctx.fillStyle = `hsla(${(frame * 4 + i * 25) % 360}, 80%, 60%, 0.25)`;
        ctx.fill();
      }

      // Center title
      ctx.fillStyle = '#f8fafc';
      ctx.font = 'bold 26px "Plus Jakarta Sans", sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(`${provider} AI Generated Video (Sample)`, width / 2, height / 2 - 15);

      ctx.fillStyle = '#38bdf8';
      ctx.font = '16px "JetBrains Mono", monospace';
      ctx.fillText(`Frame ${frame + 1}/90 | Time: ${time.toFixed(2)}s`, width / 2, height / 2 + 25);

      // Watermark in bottom right
      this.drawWatermarkBadge(ctx, width, height, provider);

      // Yield frame
      await new Promise((r) => setTimeout(r, 16));
    }

    recorder.stop();

    return new Promise((resolve) => {
      recorder.onstop = () => {
        const blob = new Blob(chunks, { type: 'video/webm' });
        const file = new File([blob], `sample_${provider.toLowerCase().replace(/\s+/g, '_')}_480p.webm`, {
          type: 'video/webm',
        });
        resolve(file);
      };
    });
  }

  private static drawWatermarkBadge(
    ctx: CanvasRenderingContext2D,
    width: number,
    height: number,
    provider: string
  ): void {
    const wmWidth = Math.round(width * 0.16);
    const wmHeight = Math.round(height * 0.08);
    const wmX = width - wmWidth - Math.round(width * 0.025);
    const wmY = height - wmHeight - Math.round(height * 0.035);

    // Semi-transparent pill background
    ctx.save();
    ctx.fillStyle = 'rgba(15, 23, 42, 0.65)';
    ctx.beginPath();
    ctx.roundRect(wmX, wmY, wmWidth, wmHeight, 8);
    ctx.fill();
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.25)';
    ctx.lineWidth = 1;
    ctx.stroke();

    // Watermark Icon & Text
    ctx.fillStyle = '#ffffff';
    ctx.font = `bold ${Math.max(12, Math.round(wmHeight * 0.38))}px "Plus Jakarta Sans", sans-serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    
    const iconPrefix = provider === 'Gemini' ? '✦ ' : provider === 'Veo 3' ? '⚡ ' : '❖ ';
    ctx.fillText(`${iconPrefix}${provider}`, wmX + wmWidth / 2, wmY + wmHeight / 2);
    ctx.restore();
  }
}
